### ISSUE TITLE
Wrong Search URLs created within Dashboards

### ISSUE THREAD

**Issue by atbunds** [billmurrin/graylog-plugin-quickvaluesplus-widget#34]
URLs all starting like
http://graylogserver.lan:9000/streams/undefined/search?q=gl2_source_input....
Should be http://graylogserver.lan:9000/search?q=gl2_source_input.... without "streams/undefined"

![image](https://user-images.githubusercontent.com/31536150/33489445-339988f4-d6b4-11e7-8788-c8e4f81381a9.png)

Error Message:
Could not retrieve Stream
Loading Stream failed with status: Error: cannot GET http://graylogserver.lan:9000/api/streams/undefined (404)

Running Graylog2 2.3.2 with Quick-Values-Plus 3.0.1

**Comment by pbr0ck3r** [comment]
@billmurrin... not sure if you have already looked into this issue or fixed it. But I did some digging. It seems that the widget config is missing `stream_id`. 

So when the following gets called the stream_id is undefined because it does not exist.

https://github.com/billmurrin/graylog-plugin-quickvaluesplus-widget/blob/0c2d5fdcb7f32cf8e955ceedd0163bd6b6cd863c/src/web/components/QuickValuesPlusVisualization.jsx#L237

**Comment by billmurrin** [comment]
Fixed in version 3.0.2. Closing.
